In [1]:
import numpy as np

In [4]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
# 2. Create a vector with values ranging from 10 to 49.
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4], dtype=int64),)


In [8]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
x = np.arange(100).reshape(10,10)
print(x.min())
print(x.max())

0
99


In [9]:
# 6. Create a random vector of size 30 and find the mean value.
x = np.random.random(30)
print(x.mean())

0.5209530872522329
